name: Kenny Doe
bio: 'Hi there, I am a software engineer based in Singapore. Currently working on changing the accounting application.'
# Site settings
title: Kenny Chan Zhi Yao
email: kenny@zenlab.me
description: > # this means to ignore newlines until "baseurl:"
  Kenny Chan's thought and random ideas on technology
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zhiyao.github.io" # the base hostname & protocol for your site
picture: /assets/images/profile.jpg
heroBg: /assets/images/polygon-image-bg.jpg

twitter_username: zhiyao
github_username:  zhiyao

# Build settings
markdown: kramdown

twitter: zhiyao
github: zhiyao

disqus: kennychan

about: true
blog: true
show-tags: true
related: true
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, ]
